spring:
  profiles: default
---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      serviceName: customers-service  
server:
  port: 8081
