vets:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  profiles: default
  cloud:
    consul:
      host: 192.168.56.102
      port: 8500
    discovery:
      serviceName: vet-service
      ip-address: 169.254.155.76
      prefer-ip-address: true
server:
  port: 8083
