spring:
  profiles: default

---
server:
  port: 8082
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
  cloud:
    consul:
      host: localhost
      port: 8500
    discovery:
      serviceName: visits-service

